"""faz2_yeni_modeller

Revision ID: 596c80bd6f18
Revises: 57d5abd94616
Create Date: 2026-05-02 02:30:33.245462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596c80bd6f18'
down_revision = '57d5abd94616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('min_discount_percent', sa.Float(), nullable=True),
    sa.Column('scrape_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deal_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('deal_score', sa.Float(), nullable=False),
    sa.Column('deal_reason', sa.String(length=500), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('previous_average_price', sa.Float(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(), nullable=True),
    sa.Column('last_detected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(length=200), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('vertical', sa.String(length=20), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('lowest_price_all_time', sa.Float(), nullable=True),
    sa.Column('lowest_price_7d', sa.Float(), nullable=True),
    sa.Column('lowest_price_30d', sa.Float(), nullable=True),
    sa.Column('lowest_price_90d', sa.Float(), nullable=True),
    sa.Column('lowest_price_180d', sa.Float(), nullable=True),
    sa.Column('average_price_7d', sa.Float(), nullable=True),
    sa.Column('average_price_30d', sa.Float(), nullable=True),
    sa.Column('average_price_90d', sa.Float(), nullable=True),
    sa.Column('days_at_current_low', sa.Integer(), nullable=True),
    sa.Column('is_all_time_low', sa.Boolean(), nullable=True),
    sa.Column('is_30d_low', sa.Boolean(), nullable=True),
    sa.Column('is_90d_low', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('found_count', sa.Integer(), nullable=True),
    sa.Column('new_product_count', sa.Integer(), nullable=True),
    sa.Column('updated_product_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['scrape_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrape_runs')
    op.drop_table('product_stats')
    op.drop_table('price_alerts')
    op.drop_table('deal_snapshots')
    op.drop_table('scrape_targets')
    # ### end Alembic commands ###
