"""faz6_alarm_type_min_discount

Revision ID: d44ca6ad98ee
Revises: a1b2c3d4e5f6
Create Date: 2026-05-02 18:32:15.676059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44ca6ad98ee'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alarm_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('min_discount_percent', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.drop_column('min_discount_percent')
        batch_op.drop_column('alarm_type')

    # ### end Alembic commands ###
